### ISSUE TITLE
Whitespace with 'white-space: pre'

### ISSUE THREAD

**Issue by shellscape** [Moveo/minimize#32]
There are a lot of situations in which we'll want to tell an element to use `pre` for white-space without using the `<pre/>` tag, rather through css. Github actually makes heavy use of this technique. With the goal of this module being to reduce the size of the resulting html, placing a `<pre/>` tag in each one of those situations negates the point. Adding margins, padding isn't an option when you're in need of that whitespace. And replacing spaces with `&emsp;` or `&nbsp;` also adds unneeded size to the resulting html.

What can be done to counteract the removal of intended whitespace between elements which have that style applied?

**Comment by Swaagie** [comment]
Afraid the module doesn't do any CSS parsing and won't either in the future, so checking by style is not feasible, that said do you have a small example that shows how this would look. Perhaps another pattern can be found that can be used for detection.

**Comment by shellscape** [comment]
@Swaagie what about `data-` attributes, or a custom `minimize-` attribute such as `minimize-pre` or some such that would act as a line-flag/option (similar to how jshint allowed per-line options). Those 'vendor' attributes could be removed in the resulting html. That'd allow some additional instruction to minimize, and be unobtrusive to the output.

**Comment by Swaagie** [comment]
This might be a nice feature for a plugin, will check if it is possible to add plugins that are run `before` and `after` minimizing. This will not be a core feature however, as it is outside the scope of html. Also not that there are 3 elements which retain their structural whitespace. See https://github.com/Moveo/minimize/blob/master/lib/list.js#L36-L39, wouldn't that cover the functionality you require?

**Comment by shellscape** [comment]
@Swaagie please do let me know what you find. 

Regarding elements which retain their whitespace, please see the original post. When dealing with email, specifically generating html emails (for many marketing and internal purposes) the focus needs to be on the size of the resulting html. Anything over 120kb and Gmail clips the message. When you're dealing with html and rudimentary html structure, it's really easy to get up to that limit. We're squeezing every KB out that we can.

It also just occurs to me that I might be able to strip out those tags after the minification, which might be another useful application for a plugin.

**Comment by Swaagie** [comment]
Started work on the plugin architecture in the [#plugin](https://github.com/Moveo/minimize/tree/plugin) branch. Async reducing is going to be a bit tricky, basically if I'm done you  should be able to hook into each element that gets crawled by the reducer.

**Comment by Swaagie** [comment]
Released as 1.3.0
