### ISSUE TITLE
Keep attribute casing

### ISSUE THREAD

**Issue by richarddavenport** [Moveo/minimize#33]
Not sure when it's happening, maybe in the html parser, but attributes that have capital letters end up being lowercased. Anyway to keep this from happening?

**Comment by Swaagie** [comment]
I think your right about it happening in the html parser, it's at least not done deliberately by minimize. Perhaps it be better to issue it there, although htmlparser2 might have good reasons to do so.

**Comment by Swaagie** [comment]
Closing this as recent dev work convinced me this is something done by htmlparser2, please issue it there :)
