### ISSUE TITLE
comments and conditionals are not treated differently

### ISSUE THREAD

**Issue by jonathanepollack** [Moveo/minimize#34]
Keeping one `true` is the same as keeping the other, or both, true (i.e. `{comments: true}` == `{conditions: true}`).

I know this was done on purpose to clean up the comments logic, but it seems like a punt. Can we go back to treating these two different?

**Comment by Swaagie** [comment]
I agree with you on this one, will check it out asap

**Comment by Swaagie** [comment]
Published as 1.3.1, I assumed you wanted to remove comments and keep conditionals here, the same goes for server side includes now. Only `comments: true` will keep all around

**Comment by jonathanepollack** [comment]
Awesome, I'll mark this in [#17](https://github.com/jonathanepollack/gulp-minify-html/issues/17).
