### ISSUE TITLE
feature: Allow hooks or plugins for custom minifiers

### ISSUE THREAD

**Issue by 3rd-Eden** [Moveo/minimize#35]
It would be nice if we were given some more control over the minification process. For example I want to be able to remove classNames and id's if they are not present in the CSS that is loaded in the page. This undertaking is probably to big and error prone to be a feature inside of minimize it as I know many more examples as well, like css compression for style attributes and tags. Minification of js files etc. This would unleash a new potential eco system for this module it self.

**Comment by Swaagie** [comment]
Couldn't agree moar, already in the pipeline https://github.com/Moveo/minimize/issues/32, will write tommorrow on the plane ;)

**Comment by Swaagie** [comment]
Started work on the plugin architecture in the [#plugin](https://github.com/Moveo/minimize/tree/plugin) branch. Async reducing is going to be a bit tricky, basically if I'm done you  should be able to hook into each element that gets crawled by the reducer.

**Comment by Swaagie** [comment]
Released as 1.3.0
