### ISSUE TITLE
CLI not found

### ISSUE THREAD

**Issue by pavel** [Moveo/minimize#36]
Hi. I've installed minimize, package.json points to **^1.2.0** version.
When I create npm script:
```
"test": "minimize --help"
```
And when I do `npm run test`, I get `minimize: command not found` from shell.

I assume `"bin"` property is missing in your `package.json`. I assume that it should be like in [jade](https://github.com/jadejs/jade/blob/master/package.json#L21-L23)

###### npm: 2.6.1, node: 0.12.0

**Comment by Swaagie** [comment]
Thx for taking the time to issue this, will be released shortly as 1.2.1
