### ISSUE TITLE
autocomplete="off" is changed to autocomplete which is opposite of meaning.

### ISSUE THREAD

**Issue by gambrose** [Moveo/minimize#42]
I have the following html

```html
<input autocomplete="off">
```
autocomplete="off" is set to prevent the browser suggesting entries in a dropdown. I want to provide my own drop down using javascript.

When minimised I get
```html
<input autocomplete>
```
Which is not semantically equivalent as this turns on autocomplete

**Comment by Swaagie** [comment]
Good spot, thx for reporting, the easiest fix would be to remove https://github.com/Moveo/minimize/blob/master/lib/list.js#L28 from the redundant list for now, I was not aware providing it with `"off"` instead of false was possible.

**Comment by Swaagie** [comment]
published fix with version 1.4.0

**Comment by gambrose** [comment]
Thanks for the quick fix.
